### ISSUE TITLE
Need Help?

### ISSUE THREAD

**Issue by shawnwildermuth** [myokyawhtun/label-edit#4]
Looks like there is a pull request from last year that is causing a bug for me. I've fixed it locally, but I wondered if you needed help maintaining the project? (PR is from Oct 2018)

**Comment by goryny4** [comment]
seems it's better to make a fork..
I'd like to have an option to enter Edit mode on Dblclick instead of a Click.

**Comment by myokyawhtun** [comment]
@shawnwildermuth and @goryny4 due to my work and my family matter, I can no longer maintain this codebase. Feel free to fork it and update on your own. Thank you!

**Comment by shawnwildermuth** [comment]
I recreated this with the Composition API and using v-model instead of text. I'll mention your project once I open source it.
